name: Lint

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python "3.11"
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --select=E9,F63,F7,F82
        # exit-zero treats all errors as warnings.
        flake8 . --exit-zero

    - name: PyLint
      # https://github.com/marketplace/actions/pylint-with-dynamic-badge
      uses: Silleellie/pylint-github-action@v2.1
      with:
        lint-path: src  # lint src package
        python-version: 3.11  # python version which will lint the package
        pylintrc-path: .pylintrc
